### ISSUE TITLE
windows python 3.x issues

### ISSUE THREAD

**Issue by systems1** [daniellawrence/graphitesend#57]
Here are some issues on windows 

D:\python\Scripts>python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import graphitesend
>>> graphitesend.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'init'

========================
D:\python>graphitesend test2 44
Traceback (most recent call last):
  File "D:\python\lib\site-packages\graphitesend\graphitesend.py", line 260, in
_dispatch_send
    sending_function(message.encode("ascii"))
  File "D:\python\lib\site-packages\graphitesend\graphitesend.py", line 291, in
_send
    self.socket.sendall(message.encode("ascii"))
AttributeError: 'bytes' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\Scripts\graphitesend-script.py", line 9, in <module>
    load_entry_point('graphitesend==0.7.0', 'console_scripts', 'graphitesend')()

  File "D:\python\lib\site-packages\graphitesend\graphitesend.py", line 623, in
cli
    graphitesend_instance.send(metric, value)
  File "D:\python\lib\site-packages\graphitesend\graphitesend.py", line 360, in
send
    return self._dispatch_send(message)
  File "D:\python\lib\site-packages\graphitesend\graphitesend.py", line 262, in
_dispatch_send
    self._handle_send_error(e)
  File "D:\python\lib\site-packages\graphitesend\graphitesend.py", line 283, in
_handle_send_error
    (self.addr, error)
graphitesend.graphitesend.GraphiteSendException: Unknown error while trying to s
end data down socket to ('ai-graphiteprd1', 2003), error: 'bytes' object has no
attribute 'encode'
=================

**Comment by daniellawrence** [comment]
@kubauk 's #60 fixes this issue :+1:
