### ISSUE TITLE
send_list fails with encoding error on python3

### ISSUE THREAD

**Issue by fake-name** [daniellawrence/graphitesend#76]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/graphitesend/graphitesend.py", line 303, in _send_and_reconnect
    self.socket.sendall(message.encode("ascii"))
AttributeError: 'bytes' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/graphitesend/graphitesend.py", line 260, in _dispatch_send
    sending_function(message.encode("ascii"))
  File "/usr/local/lib/python3.5/dist-packages/graphitesend/graphitesend.py", line 308, in _send_and_reconnect
    self.socket.sendall(message.encode("ascii"))
AttributeError: 'bytes' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zerorpc/core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/usr/local/lib/python3.5/dist-packages/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/usr/local/lib/python3.5/dist-packages/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "/media/Storage/Scripts/ReadableWebProxy/FetchAgent/server.py", line 103, in putJob
    self._put_metric("Fetch.Get.{}.count".format(queuename), 1)
  File "/media/Storage/Scripts/ReadableWebProxy/FetchAgent/server.py", line 89, in _put_metric
    self.mon_con.send_list(tosend)
  File "/usr/local/lib/python3.5/dist-packages/graphitesend/graphitesend.py", line 445, in send_list
    return self._dispatch_send(message)
  File "/usr/local/lib/python3.5/dist-packages/graphitesend/graphitesend.py", line 262, in _dispatch_send
    self._handle_send_error(e)
  File "/usr/local/lib/python3.5/dist-packages/graphitesend/graphitesend.py", line 283, in _handle_send_error
    (self.addr, error)
graphitesend.graphitesend.GraphiteSendException: Unknown error while trying to send data down socket to ('10.1.1.56', 2003), error: 'bytes' object has no attribute 'encode'

```

This is with a `GraphitePickleClient()` instance. 

Instantiation:

```
		self.mon_con = graphitesend.GraphitePickleClient(
				autoreconnect   = True,
				group           = None,
				prefix          = 'ReadableWebProxy.FetchAgent',
				system_name     = '',
				graphite_server = settings.GRAPHITE_DB_IP,
				graphite_port   = 2003,
				debug           = True,
				clean_metric_name = True,
			)
```

**Comment by fake-name** [comment]
Never mind. I'm a derp, and thought I had updated to the latest from git, but pip assumed because the version number in git is still 0.7.0, no update was needed.
