### ISSUE TITLE
asynchronous send caused memory leak

### ISSUE THREAD

**Issue by christophetrinh** [daniellawrence/graphitesend#83]
Hello,

I'm load testing a simple 'hello world' API using [locust](https://locust.io/).

It seems that using graphitesend in an asynchronous mode while stressing the API (500 users requesting the same endpoint, ~35 requests per secs), create memory leaks. 

Memory leak appears after this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.6/site-packages/graphitesend/graphitesend.py", line 307, in _send_and_reconnect
    self.socket.sendall(message.encode("ascii"))
  File "/usr/local/lib/python3.6/site-packages/gevent/_socket3.py", line 458, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.6/site-packages/gevent/_socketcommon.py", line 355, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.6/site-packages/gevent/_socketcommon.py", line 295, in __send_chunk
    data_sent += socket.send(chunk, flags, timeout=timeleft)
  File "/usr/local/lib/python3.6/site-packages/gevent/_socket3.py", line 443, in send
    self._wait(self._write_event)
  File "src/gevent/_hub_primitives.py", line 265, in gevent.__hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 266, in gevent.__hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 245, in gevent.__hub_primitives._primitive_wait
gevent.exceptions.ConcurrentObjectUseError: This socket is already used by another greenlet: <bound method Waiter.switch of <gevent.__waiter.Waiter object at 0x7f8b1bc67e58>>
2018-11-26T15:44:31Z <Greenlet "Greenlet-0" at 0x7f8b1bc28c48: <bound method GraphiteClient._send_and_reconnect of <graphitesend.graphitesend.GraphiteClient object at 0x7f8b181153c8>> failed with ConcurrentObjectUseError
```

Using graphitesend without asynchronous mode doesn't create any memory leak.

Code ex:
```
from flask import Flask
from graphite import GraphiteClient

# we need to patch sockets to make requests async
from gevent import monkey
monkey.patch_all()

app = Flask(__name__)

try:
    config = {
        'graphite_server': '<GRAPHITE_SERV_NAME>',
        'graphite_port': <GRAPHITE_PORT>,
        'prefix': 'graphite',
        'asynchronous': True,
        'autoreconnect': True,
        'dryrun': False
    }
    graphite = GraphiteClient(**config)
    print('Graphite client has been initialized.')
except:
    print('Cannot initialize Graphite client.')


@app.route("/")
def hello():
    tmp = ['test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test']
    print(tmp)
    graphite.send('metric1', 2)
    return "Hello World!"


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8083)
```

The API is running using uWSGI (2.0.17.1), graphitesend (0.10.0), gevent (1.2.1) Flask (0.12) and python 3.6.4

**Comment by christophetrinh** [comment]
mb sorry, It seems it's not coming from graphitesend, but from flask-graphite in async mode.

**Comment by Shir0kamii** [comment]
Hi!

Thanks for reporting! I'm also the autor of flask-graphite, so feel free to open another issue there and tell us your latest findings, we'll do our best to help you.

For the record, the async code in graphitesender is messy anyway, I plan to remove it and offer async feature in the form of a subclass.

**Comment by manawasp** [comment]
Hello @Shir0kamii 

I focused on this issue :
Graphitesend async mode generate exception under pressure (which looks also leaking, gevent issue) cause in async mode it still use one socket shared for every greenlet, which is not possible in concurrent mode, I recommand to use a socket pool.

Any help wanted for this ?

**Comment by Shir0kamii** [comment]
Hi @Manawasp 

I could use some help on this, but if you contribute, please do so on https://github.com/Shir0kamii/graphitesender, since I can't publish graphitesend on Pypi.

I like your solution to use a socket pool, but could you implement it in a subclass of the client ? rather than having a boolean at initialization, deciding wether to toggle async.

Thank you for the interest!

**Comment by ramnes** [comment]
@Shir0kamii maybe reopen this?

**Comment by Shir0kamii** [comment]
@ramnes I made a copy in the fork referencing this issue instead
